name: TrizoneWebLink
version: 1.3.2
main: fr.trizone.weblink.TrizoneWebLink
api-version: '1.21'
author: trigameYT
description: Liaison Trizone + livraison Stripe + synchro inventaire et Ender Chest du Lobby.
softdepend: [LuckPerms]
commands:
  link:
    description: Lie ou synchronise ton compte Minecraft avec Trizone.
    usage: /link <code|sync>
    permission: trizone.weblink.use
permissions:
  trizone.weblink.use:
    default: true
