name: TrizoneWebLink
version: 1.0.0
main: fr.trizone.weblink.TrizoneWebLink
api-version: '1.21'
author: trigameYT
description: Liaison sécurisée entre les comptes du site Trizone et Minecraft.
commands:
  link:
    description: Lie ton compte Minecraft à ton compte Trizone.
    usage: /link <code>
    permission: trizone.weblink.use
permissions:
  trizone.weblink.use:
    default: true
